Feature - Updated readme to provide detailed instructions
weaviate-tutorials/DEMO-image-search-dogs pull request #6
Opened 2023-10-25 15:56 UTC by AryanSankholkar

@iamleonie 

Hi, I have completed your readme for this project as required in the task.

2023-10-26 06:55 UTC, iamleonie requested changes
Hi @AryanSankholkar,
Thank you for your contribution. As our demos follow a simple template for the README.md file it would be great if you could keep your changes within the defined structure:
# [Title]
## Description
(description + demo video)
## Used Technologies
(Used technology stack + used Weaviate modules)
## Prerequisites

# Setup instructions

# Usage instructions

# Dataset license

Thank you so much.

2023-10-26 06:55 UTC, iamleonie commented on readme.md
> -This project's origin is [here](https://github.com/weaviate/weaviate-examples/tree/main/nearest-neighbor-dog-search).
Please keep this line

2023-10-26 06:55 UTC, iamleonie commented on readme.md
> -## Dataset license
Please keep the dataset license

2023-10-29 13:30 UTC, AryanSankholkar commented
@iamleonie I have made the required changes in the readme file....Please have a look!

2023-10-30 07:47 UTC, iamleonie requested changes
Hey @AryanSankholkar, Thank you for implementing the requested changes. After the second review, I have added a few new comments regarding sections, where you were overwriting some important parts of the README.md file. 

What I usually recommend is to use a file comparison tool (e.g., native in VS Code, or Beyond Compare) to double-check that the changes you make are adding value and not removing important parts.

While we appreciate every contribution, it is important that they keep our projects in good health. Please let me know if you have any questions.

2023-10-30 07:47 UTC, iamleonie commented on readme.md
> -(TODO: Add demo video)
Let's keep this line as well, so future contributors know that there is a TO DO here.

2023-10-30 07:47 UTC, iamleonie commented on readme.md
> -   python -m venv .venv
Please keep the setup of the virtual environment in the setup instructions

2023-10-30 07:47 UTC, iamleonie commented on readme.md
> -    pip install -r requirements.txt
Please also keep the installation of required packages in the setup instructions

2023-10-30 07:47 UTC, iamleonie commented on readme.md
> -### Run the query
Please also keep the step to run the query.py file

2023-10-30 08:39 UTC, AryanSankholkar commented
have also made the required changes...Please have a look!!

2023-10-30 10:00 UTC, iamleonie requested changes
Hey, 
thanks for the updates again. 
It looks like a lot of the contributions from your previous commit got lost... (e.g., the description, Weaviate modules, explanation of what the images-to-base64.py does, running the test file), also the first line ("The project's origin is here...) was removed again. Could you please review and double-check your changes?

2023-10-30 10:00 UTC, iamleonie commented on readme.md
> -This project's origin is [here](https://github.com/weaviate/weaviate-examples/tree/main/nearest-neighbor-dog-search).
Hey, this got lost in your last commit again.

2023-10-30 10:00 UTC, iamleonie commented on readme.md
> +- [List the Weaviate modules used]
It looks like the module from your previous commit got lost?

2023-10-31 14:27 UTC, AryanSankholkar commented
Hi @iamleonie ,

I have once more updated the readme and this time with the correct changes. I am truly sorry for having to bother you again and again

I have added these parts back in the readme

> # Dog Search 
> 
> This project's origin is [here](https://github.com/weaviate/weaviate-examples/tree/main/nearest-neighbor-dog-search).

> **Weaviate Modules:**
> 
> [Image Vectorization](https://github.com/AryanSankholkar/DEMO-image-search-dogs/tree/feature/newfeature#image-vectorization)
> In this demonstration, we will work with a dataset of dog images. The current dataset includes ten images of different dog breeds. However, you can easily replace these images with any other dataset to suit your specific use case. To do this, add your images to the flask-app/static/img folder and execute the images-to-base64.py and upload-data-objects.py files.
> 
> For this use case, it's essential that image vectorization captures information about the dogs, such as breed, size, and color. Weaviate's img2vec-neural module is designed to solve this problem. It vectorizes each image, enabling semantic similarity-based searches.
> 
> [Img2vec-neural Module](https://github.com/AryanSankholkar/DEMO-image-search-dogs/tree/feature/newfeature#img2vec-neural-module)
> Weaviate's img2vec-neural module is a flexible vectorizer that converts images into meaningful vectors. It supports the ResNet-50 model, a Convolutional Neural Network (CNN) trained on the ImageNet database, which contains over 10 million images and 20,000 classes.

2023-11-01 08:33 UTC, iamleonie approved these changes
Thank you for your hard work on this. I will merge this now.

2023-11-01 08:33 UTC, merged

2023-11-01 10:17 UTC, iamleonie commented
Related to https://github.com/weaviate-tutorials/DEMO-image-search-dogs/issues/1

2023-11-02 09:53 UTC, iamleonie commented
Hey @AryanSankholkar,
Thank you for your contribution during Hacktoberfest 2023.
We'd like to send you some SWAG as a little thank you.
Would it be possible for you to reach out via our [Weaviate Slack](https://weaviate.io/slack) to discuss details?
Otherwise, please let me know how I can reach you best (e.g., LinkedIn, Twitter)
Thanks again and best regards
Leonie

2023-11-02 12:53 UTC, AryanSankholkar commented
you can reach me out through linkedin.... i have followed you too in linkedin.....my linkedin profle is Aryan Sankholkar